
CREATE TABLE units (
    host TEXT NOT NULL,
    unit TEXT NOT NULL,
    ts TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE journal (
    host TEXT NOT NULL,
    id TEXT NOT NULL,
    priority SMALLINT NOT NULL,
    message TEXT NOT NULL,
    ts TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE hackers (
    address TEXT NOT NULL,
    method TEXT NOT NULL,
    ts TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
